name = "cfworker-ai-api"                # todo
main = "index.js"
compatibility_date = "2024-05-06"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"
preview_bucket_name = "ai-images"

[vars]
CLOUDFLARE_ACCOUNT_ID = "cd9f507ccf54931ef83e7dda8e3f0082" # replace with your own.
MODEL_MAPPER = { "gpt-3.5-turbo" = "@cf/meta/llama-3-8b-instruct" } # Optional
